import './globals.css'
import { Inter } from 'next/font/google'
// import "../public/img/favicon.ico";
// import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Google Notes',
  description: 'Generated by Aliyan , Hasnain',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>{children}</body>
    </html>
  )
}
