import Login from "@/app/components/organisims/Login";
import Head from "next/head";



function index () {
    return ( 
        <>
            <Head>
                <link rel="icon" type="image/x-icon" href="/img/favicon.ico"></link>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>Signup| Keep notes</title>
            </Head>
            <Login/>
        </>
    )
}

export default index ;