import React from 'react'
import Head from 'next/head';
import Validation from '@/app/components/organisims/Validation';
import { UserProvider } from '@/app/components/Context/ContextProvider';


function Signin() {
  return (
    // <UserProvider>
    <>
      <Head>
        <link rel="icon" type="image/x-icon" href="/img/favicon.ico"></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Signin | Keep notes</title>
      </Head>
      <Validation />
    </>
    // </UserProvider>
  );
}

export default Signin;