import Navbar from "@/app/components/organisims/Navbar";
import Sidenav from "@/app/components/organisims/Sidenav";
import MainSection from "@/app/components/organisims/MainSection";
// import { useEffect, useState } from "react";
import Styles from './pages.css'
import {UserProvider} from "@/app/components/Context/ContextProvider";
import Head from "next/head";
import { useRouter } from "next/router";
import SearchProvider from "@/app/components/Context/SearchProvider";
import ComponentProvider from "@/app/components/Context/ComponentProvider";


function Start() {



  return (
    // <UserProvider>
    <>
      <Head>
        <link rel="icon" type="image/x-icon" href="/img/favicon.ico"></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>Google Keep </title>
      </Head>
      <ComponentProvider>
        <SearchProvider>
          <main>
            <Navbar />
            <Sidenav />
            <MainSection />
          </main>
        </SearchProvider>
      </ComponentProvider>
    </>
    // </UserProvider>
  );
}

export default Start;
